name: Build and Release Python Application

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    name: Build Windows executable
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Build executable with PyInstaller
      run: |
        pyinstaller --onefile --windowed zrbin2sql.py

    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: WindowsExecutable
        path: dist/zrbin2sql.exe

  build-linux:
    name: Build Linux executable
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile --noconsole zrbin2sql.py

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: LinuxExecutable
          path: dist/zrbin2sql

  release:
    name: Create GitHub Release
    needs: [build-windows, build-linux]
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
    - name: Download Windows artifact
      uses: actions/download-artifact@v4
      with:
        name: WindowsExecutable
        path: dist

    - name: Download Linux artifact
      uses: actions/download-artifact@v4
      with:
        name: LinuxExecutable
        path: dist
      run: ls -R

#    - name: Make Linux executable
#      run: chmod +x LinuxExecutable/zrbin2sql

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          WindowsExecutable/zrbin2sql.exe
          LinuxExecutable/zrbin2sql
        draft: true