name: Build and Release Python Application

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    name: Build Windows executable
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Build executable with PyInstaller
      run: |
        pyinstaller --onefile --windowed zrbin2sql.py

    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: WindowsExecutable
        path: dist/zrbin2sql.exe

  build-linux:
    name: Build Linux executable
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile --noconsole zrbin2sql.py

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: LinuxExecutable
          path: dist/zrbin2sql

  release:
    name: Create GitHub Release
    needs: [build-windows, build-linux]
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
    - name: Download Windows artifact
      uses: actions/download-artifact@v4
      with:
        name: WindowsExecutable
        merge-multiple: true

    - name: Download Linux artifact
      uses: actions/download-artifact@v4
      with:
        name: LinuxExecutable
        merge-multiple: true

    - name: create release
      id: create-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: zrbin2sql
        draft: false
        prerelease: false

    - name: upload release asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: .
        asset_name: |
          zrbin2sql
          zrbin2sql.exe
        asset_content_type: application/octet-stream